[package]
name = "lvs"
version = "0.1.0"
edition = "2021"

[dependencies]
foundation = { path = "../../lib/verifire.lib.foundation" }
log = "0.4.21"
serde = { version = "1.0.204", features = ["derive"] }
