pub(crate) mod doc;
mod task_angle;
mod task_enc_poly;
mod task_enc_rect;
mod task_exact_size;
mod task_min_area;
mod task_min_max_width;
mod task_notch_error;
mod task_off_grid;
mod task_spacing;
mod task_filter;
mod task_extension;
mod task_density;
mod task_check_shape;
mod task_slit_length;
mod task_connectivity;
mod task_lvs;